name: poc-pipeline
on:
  push:
    branches:
      - 'feature/*'
jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: <a href="mailto:actions/checkout@v4" rel="noreferrer noopener" title="mailto:actions/checkout@v4" target="_blank">actions/checkout@v4</a>